Vagrant.configure("2") do |config|
  config.vm.box = "archlinux"
  config.vm.provision "shell", privileged: false, path: "user/provision/10-fish.sh"
  config.vm.provision "shell", privileged: false, inline: "[[ -e /vagrant/user/files ]] && cp -r /vagrant/user/files/. ~"
end
