Vagrant.configure("2") do |config|
  config.vm.box = "archlinux"
  config.vm.provider "virtualbox" do |v| v.gui = true end
  config.vm.provision "shell", path: "provision/10-timezone.sh"
  config.vm.provision "shell", path: "provision/20-locale.sh"
  config.vm.provision "shell", path: "provision/30-pacman.sh"
  config.vm.provision "shell", path: "provision/40-swap.sh"
  config.vm.provision "shell", privileged: false, path: "user/provision/10-fish.sh"
  config.vm.provision "shell", privileged: false, inline: "[[ -e /vagrant/user/files ]] && cp -r /vagrant/user/files/. ~"
end
