Vagrant.configure("2") do |config|
  config.vm.box = "archlinux"
  config.vm.provider "virtualbox" do |v| v.gui = true end
  config.vm.provision "shell", privileged: false, path: "provision/sway.sh"
end
