Vagrant.configure("2") do |config|
  config.vm.box = "archlinux"
  config.vm.provision "shell", path: "provision/10-timezone.sh"
  config.vm.provision "shell", path: "provision/20-locale.sh"
  config.vm.provision "shell", path: "provision/30-pacman.sh"
end
