Vagrant.configure("2") do |config|
  config.vm.box = "archlinux"
  config.vm.provision "shell", inline: "pacman --noconfirm --sync --refresh --sysupgrade > /dev/null"
  config.vm.provision "shell", path: "provision/locale.sh"
end
