Vagrant.configure("2") do |config|
  config.vm.box = "archlinux-minimal"
  config.vm.provision :shell, path: "provision/10-timezone.sh"
  config.vm.provision :shell, path: "provision/20-locale.sh"
  config.vm.provision :shell, path: "provision/30-pacman.sh"
  config.vm.provision :shell, path: "provision/40-swap.sh"
end
