Vagrant.configure("2") do |config|
  config.vm.box = "archlinux"
  config.vm.provider "virtualbox" do |v| v.gui = true end
  config.vm.provision "shell", inline: "pacman --noconfirm --sync --refresh --sysupgrade > /dev/null"
  config.vm.provision "shell", path: "files/install.sh"
  config.vm.provision "shell", path: "provision/swap.sh"
  config.vm.provision "shell", path: "provision/locale.sh"
  config.vm.provision "shell", path: "provision/pacman.sh"
  config.vm.provision "shell", path: "provision/xorg.sh"
  config.vm.provision "shell", path: "provision/bspwm.sh"
  config.vm.provision "shell", path: "provision/rice.sh"
  config.vm.provision "shell", inline: "systemctl --quiet restart getty@tty1"
end
